dict = dict(logUrl=r'C:\\Python27\\atlas-master\\atlas\\mysite\\atlas\\PyScripts\\Outputs\Log\\',
            outputUrl=r'C:\\Python27\\atlas-master\\atlas\\mysite\\atlas\\database\\ATLAS_Universal_2.csv',
            outputPath=r'C:\\Python27\\atlas-master\\atlas\\mysite\\atlas\\database\\Outputs\\',
            requestUrl=r'C:\\Python27\\atlas-master\\atlas\\mysite\\atlas\\database\\request.csv',
            amazonOutput=r'C:\\Python27\\atlas-master\\atlas\\mysite\\atlas\\PyScripts\\Outputs\\Amazon_I\\',
            homedepotOutput='C:\\Python27\\atlas-master\\atlas\\mysite\\atlas\\PyScripts\\Outputs\\HomeDepot\\',
            chromeDriver=r'C:\\Python27\\atlas-master\\atlas\\mysite\\atlas\\chromedriver.exe',
            keywordsDict=r'C:\\Python27\\atlas-master\\atlas\\mysite\\atlas\\database\\keywordsSubTD.csv',
            tdDictsPath=r'C:\\Python27\\atlas-master\\atlas\\mysite\\atlas\\database\\TrigDrivDicts\\',
            tri_dri_Output=r'C:\\Python27\\atlas-master\\atlas\\mysite\\atlas\\database\\Outputs\\Triggers-Drivers\\',
            sentDict=r'C:\\Python27\\atlas-master\\atlas\\mysite\\atlas\\database\\AFINN-111.txt',
            sentDictsPath=r'C:\\Python27\\atlas-master\\atlas\\mysite\\atlas\\database\\SentiDicts\\',
            uploadsUrl=r'C:\\Python27\\atlas-master\\atlas\\mysite\\atlas\\database\\uploads\\',
            topicViz=r'C:\\Python27\\atlas-master\\atlas\\mysite\\atlas\\templates\\atlas\\includes\\',
            topicModels=r'C:\\Python27\\atlas-master\\atlas\\mysite\\atlas\\database\\topicmodel\\models\\',
            logosPath=r'C:\\Python27\\atlas-master\\atlas\\mysite\\atlas\\static\\atlas\\images\\icons',
            sourcesUrl=r'C:\\Python27\\atlas-master\\atlas\\mysite\\atlas\\database\\sourceMap.csv',
            )
